project: demo
data_dir: ./data
backend:
  uri: ./data/demo
script: demo_utils
nodes:
  - name: person
    file: ./data/persons.parquet
    key: PID
    label: label
    features: features
    mode: mode
  - name: drug
    file: ./data/drugs.parquet
    key: PID
    label: label_a
    features: features
  - name: diagnosis
    file: ./data/diagnoses.parquet
    key: PID
    label: label_i
    features: features
edges:
  - name: assigned_to
    from: diagnosis
    to: person
    transform: edges_diagnosis
  - name: consumed_by
    from: drug
    to: person
    transform: edges_drugs
task:
  target_entity: person
  train_inds: ./data/train_ids.parquet
  test_inds: ./data/test_ids.parquet
  model: GraphLevelGNN
  model_args:
    aggr: "max"
    debug: True
  batch_size: 32
  optimizer: Adam
  optimizer_args:
    lr: 0.01
  model_checkpoints: ./models/checkpoint.pt