project: demo_loans
data_dir: ./data
backend:
  uri: ./data/demo_loans
script: demo_loan_utils
nodes:
  - name: loan
    file: ./data/loan.parquet
    key: label
    label: label
    features: features
    mode: mode
  - name: trans
    file: ./data/trans.parquet
    key: label
    label: label
    features: features
edges:
  - name: assigned_to
    from: trans
    to: loan
    transform: edges_trans
task:
  target_entity: loan
  train_inds: ./data/train_loan_ids.parquet
  test_inds: ./data/test_loan_ids.parquet
  model: GraphLevelGNN
  model_args:
    hidden_size: 32
    num_classes: 2
  heteromodel_args:
    aggr: "max"
    debug: True
  batch_size: 32
  optimizer: Adam
  optimizer_args:
    lr: 0.01
  model_checkpoints: ./models/checkpoint_loan.pt